# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    
    # Set up
    echo "Setting Up."
    mkdir tmp
    echo ${PWD}
    ls -R ${PWD}

    # Deloy Docker Virt Server
    echo "Deploy Parasoft SOAVirt Server."
    docker run -d \
    -p 9080:9080 \
    -e ACCEPT_EULA=true \
    --name soavirt-server parasoft/soavirt-server
    
    # Wait for Server to stand up
    sleep 15s
    
    # Apply License
    curl -X PUT "http://localhost:9080/soavirt/api/v6/preferences/config" \
    -u admin:admin \
    -H "accept: application/json" \
    -H "Content-Type: application/json" \
    -d "{\"license\":{\"licenseServer\":{\"host\":\"$(license.server.host)\",\"port\":$(license.server.port),\"useSpecifiedServer\":true,\"connectionType\":\"http\",\"authEnabled\":true,\"username\":\"admin\",\"password\":\"$(license.server.password)\"},\"virtualize\":{\"enabled\":true,\"useNetwork\":true,\"network\":{\"edition\":\"performance_server_edition\"}}}}"

    # Healthcheck Parasoft SOAVirt Server
    echo "Ping SOAVirt."
    curl -u admin:admin http://localhost:9080/soavirt/api/v6/status -o tmp/server-hc.json
    ls -R
    cat tmp/server-hc.json
  displayName: 'Deploy SOAVirt Server'

- script: |
    echo "Upload PVA."

    for file in virt/*
    do
      echo ${file}
      curl -iv --raw \
      -X POST \
      -u admin:admin \
      --data-urlencode "id=/VirtualAssets/${file}" \
      --data-urlencode "deploy=true" \
      http://localhost:9080/soavirt/api/v6/files/upload \
      -H "accept: application/json" \
      -H "Content-Type: multipart/form-data" \
      -F file=@${file} -o ${file}-upload.json
      
      echo -e "\nDebug.\n"
      cat ${file}-upload.json
    done

  displayName: 'Deploy PVA'

- script: |
    echo "Test PVA."
    curl -v http://localhost:9080
    curl http://localhost:9080/virt/HelloWorld -o test.json
    cat test.json
  displayName: 'Test PVA'
